version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: weather
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
